name: "[Check] fw releases"

on: [pull_request]

jobs:
  check_releases:
    name: Check releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: "true"
      - uses: actions/setup-python@v5
      - run: python check_releases.py

  releases-revision-checks:
    name: Check firmware releases revisions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check releases.json files changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            releases-json:
              - 'firmware/t1b1/releases.json'
              - 'firmware/1/releases.json'
              - 'firmware/t2t1/releases.json'
              - 'firmware/2/releases.json'
        if: steps.changes.outputs.releases-json == 'true'
      - name: Check releases.json revisions
        run: ./scripts/check-all-firmware-revisions.sh
