name: Releases Check

on: [pull_request]

jobs:
  check_releases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: "true"
    - uses: actions/setup-python@v4
    - run: python check_releases.py
