name: deploy - data.trezor.io

on:
  push:
    branches:
      - "master"

jobs:
  deploy_data:
    environment: production
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: "true"
      - name: Setup python
        uses: actions/setup-python@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Run release script
        run: ./ci/s3sync.sh
